version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm cit
  publish_to_npm:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npx occ ${CIRCLE_TAG##v}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
      - run: npm publish --access public 
workflows:
  version: 2
  test:
    jobs:
      - test
      - publish_to_npm:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/