version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm cit
      - run: npx @commitlint/cli --from=origin/master --to=HEAD --verbose
  publish_to_npm:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm run semantic-release
workflows:
  version: 2
  test:
    jobs:
      - test
      - publish_to_npm:
          filters:
            branches:
              only: master