version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - run: npm cit
  publish_to_npm:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - run: npm ci
      - run: npm publish

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - publish_to_npm:
          filters:
            branches:
              only: master
